title: Welcome to Revenol
description: "Ah, 'All things come to those who wait.'..."
google_analytics: true
show_downloads: true
theme: jekyll-theme-cayman
repository: revenol/revenol.github.io

gems:
  - jekyll-mentions
